---
- name: add kubernets repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    force: yes

- name: install kubeadmn
  yum:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - kubelet 
    - kubeadm 
    - kubectl