---
- name: install epel-release
  yum:
    update_cache: yes
    name: epel-release
    enablerepo: extras
    state: installed

- name: install pip
  yum:
    update_cache: yes
    name: python-pip
    state: installed

- name: update pip
  pip:
    name: pip
    state: latest

- name: install selinux
  pip:
    name: selinux
    state: latest
