- name: create xfs file system for docker
  filesystem:
    fstype: xfs
    dev: /dev/vdb
    opts: -n ftype=1

- name: make mount directory for docker
  file:
      state: directory
      path: /mnt/docker

- name: mount the docker volume 
  mount:
    path: /mnt/docker
    src: /dev/vdb
    state: mounted
    fstype: xfs